### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by kipdotcom** [vinkla/laravel-hashids#100]
Is there a branch for laravel 5.6? I don't want to upgrade to Laravel 5.7 yet but it seems there is no other way to install it without upgrading to 5.7.

Kind regards,
Joseph.

**Comment by GrahamCampbell** [comment]
https://github.com/vinkla/laravel-hashids/tree/5.0.0

**Comment by vinkla** [comment]
As @GrahamCampbell already have stated, install version 5.0. 

Please always search issues before opening new ones: #96, #99

**Comment by kipdotcom** [comment]
My apologies. Noted.
