### ISSUE TITLE
Existing ids could unknowingly change when updating composer

### ISSUE THREAD

**Issue by robido** [vinkla/laravel-hashids#102]
Based on [the hashids docs](https://hashids.org/php/#compatibility) your composer should specify an exact version of hashids. So I suggest replacing:
`"hashids/hashids": "^3.0",`
by 
`"hashids/hashids": "3.0.0",`

Right now, I specify a fixed version of your project in my composer like so:
`"vinkla/hashids": "5.1.0",`

If the developpers of hashids make a small change in the generation algo, the ids could change after I run the composer update command.

A change in ids would break the SEO of my website and I might not even notice it.

**Comment by vinkla** [comment]
You don't need to worry about this. If `hashids/hashids` updates the algorithm they will release it as a [major version](https://semver.org/). When they release a major version I'll release a major version of this package as well. It should be fine using version `^5.1` in your `composer.json` file. Updates to version 5 or later wont break the algorithm.

**Comment by robido** [comment]
Tack!
