### ISSUE TITLE
Missing BC Math or GMP extension

### ISSUE THREAD

**Issue by mahdi2608** [vinkla/laravel-hashids#110]
using PHP 7.2.17-0ubuntu0.18.04.1
and with php -m I have
[PHP Modules]
bcmath
...
gmp
...
and
laravel 5.8
--update
even I add [danhunsaker/bcmath](https://packagist.org/packages/danhunsaker/bcmath) to my packages

**Comment by vinkla** [comment]
The [danhunsaker/bcmath](https://packagist.org/packages/danhunsaker/bcmath) package wont install `ext-bcmath` in PHP. This is probably something in your environment and not an issue with this package.
