### ISSUE TITLE
getRouteKey() method not working 

### ISSUE THREAD

**Issue by Jagadhissh** [vinkla/laravel-hashids#111]
https://sampo.co.uk/blog/masking-ids-in-urls-using-hash-ids-in-laravel
regarding above url  bellow getRouteKey not working 
atleast its not responding for any error
 public function getRouteKey()
    {
        return \Hashids::connection(get_called_class())->encode($this->getKey());
    }
please give me the solution iam strugling eith this from last 4 days

**Comment by vinkla** [comment]
This is not an issue with this package. I would suggest to ask @BenSampo.
