### ISSUE TITLE
Class hashids does not exist

### ISSUE THREAD

**Issue by lsmith77** [vinkla/laravel-hashids#116]
I have the package running fine locally using homestead but on platform.sh also using PHP 7.3 I get the following error in any controller using the Hashid fascade:

```
[previous exception] [object] (ReflectionException(code: -1): Class hashids does not exist at /app/vendor/laravel/framework/src/Illuminate/Container/Container.php:804)
```

Any idea what could cause this?

**Comment by vinkla** [comment]
No, sorry.

**Comment by lsmith77** [comment]
FYI the issue was fixed by explicitly enabling the provider in the app config. I am not sure why locally auto-discovery works and remotely it doesn't.

**Comment by javeedrahman** [comment]
any update on this? @lsmith77 .
Locally works but not on remote.

**Comment by lsmith77** [comment]
no .. didn’t investigate further since explicitly enabling solved the issue.
