### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by oligoca** [vinkla/laravel-hashids#117]
Any planes for laravel 6?

**Comment by RobertCordes** [comment]
I was just trying to update my dependencies when I got an error. As it turns out Laravel 6 support is already there, I just had the wrong version of this package. Take a look at your composer.json, I had to change it to version 7.

`"vinkla/hashids": "^6.0",` to `"vinkla/hashids": "^7.0",`

**Comment by oligoca** [comment]
thank you Rob.  Works now.

**Comment by FaiyazMdAbdul** [comment]
> I was just trying to update my dependencies when I got an error. As it turns out Laravel 6 support is already there, I just had the wrong version of this package. Take a look at your composer.json, I had to change it to version 7.
> 
> `"vinkla/hashids": "^6.0",` to `"vinkla/hashids": "^7.0",`

for those who can't install , put version number inside quotes
composer require "vinkla/hashids:^7.0"
