### ISSUE TITLE
Can not install on laravel 6.15.0

### ISSUE THREAD

**Issue by shirazsoft** [vinkla/laravel-hashids#121]
Hello,
I get this error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vinkla/hashids ^8.0 -> satisfiable by vinkla/hashids[8.0.0, 8.0.x-dev].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.15.0
    - don't install illuminate/support 7.x-dev|remove laravel/framework v6.15.0
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.15.0
    - Conclusion: install illuminate/support 7.x-dev
    - Installation request for laravel/framework (locked at v6.15.0, required as ^6.2) -> satisfiable by laravel/framework[v6.15.0].

**Comment by vinkla** [comment]
https://github.com/vinkla/laravel-hashids/issues/117#issuecomment-566144143
https://github.com/vinkla/laravel-hashids/issues/114#issuecomment-528817191

**Comment by shirazsoft** [comment]
@vinkla 

Not work.
Using version ^8.0 for vinkla/hashids
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vinkla/hashids ^8.0 -> satisfiable by vinkla/hashids[8.0.0, 8.0.x-dev].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.15.0
    - don't install illuminate/support 7.x-dev|remove laravel/framework v6.15.0
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.15.0
    - Conclusion: install illuminate/support 7.x-dev
    - Installation request for laravel/framework (locked at v6.15.0, required as ^6.2) -> satisfiable by laravel/framework[v6.15.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by vinkla** [comment]
> Using version ^8.0 for vinkla/hashids...

Try 7.0.
