### ISSUE TITLE
Hashes not unique

### ISSUE THREAD

**Issue by Nizari** [vinkla/laravel-hashids#124]
Hello,

First of thank you for this package. The idea itself would be amazing since you wouldn't need anymore uuids which are impactful on performance. However i try to test if the hashes are unique with the following setting:

```php
        'main' => [
            'salt'   => 'GR4qze7Qb8rZdvx9lgAw1p6NnElB0JDW',
            'length' => '50',
        ],
```

I just want to fill a database of at least a few million, bu already after id 93 and 105 are equal!? I hope I do something wrong and you know what goes wrong.

```php
dd(Hashids::encode(93),Hashids::encode(105),Hashids::decode('G1gQAd2pbvj3N8naB4owPlrZRboZWRGe09LkEDX5YyV7OJzxqK'));
```

outputs

```php
^ "G1gQAd2pbvj3N8naB4owPlrZRboZWRGe09LkEDX5YyV7OJzxqK"
^ "G1gQAd2pbvj3N8naB4owPlrZRbOZWRGe09LkEDX5YyV7OJzxqK"
^ array:1 [
  0 => 93
]```

**Comment by vinkla** [comment]
Please submit a pull request to the [`vinkla/hashids`](https://github.com/vinkla/hashids) repository with a test case in the `HashidsTest.php` class. Once the test suite shows an error we can continue digging into this issue.

**Comment by Nizari** [comment]
@vinkla thank you for your reply, I’ll do that. However, when I try to make the test I get a strange situation where I do get the same results, however php does not recognize it as the same string...I’ll add some more descriptions with a test in the PR.

**Comment by Nizari** [comment]
@vinkla a small update (and for people cooping with the same problem), the ids are identical except for 1 letter which is capitalised. However for this reason apparently it doesn't recognise this for mysql ( I had a unique key there). So the solution is to validate that mysql (on mac at least) can coop with capitalization

**Comment by vinkla** [comment]
Yes, I actually guessed this could be the issue. This has come up before. I would recommend not to save the hashids in the database. Instead keep ids as integers and convert them before sending them to the user instead.
