### ISSUE TITLE
does not support laravel 7.0.4

### ISSUE THREAD

**Issue by sabaya99** [vinkla/laravel-hashids#127]
- vinkla/hashids 7.0.0 requires illuminate/contracts ^6.0 -> satisfiable by illuminate/contracts[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/contracts 6.x-dev|don't install laravel/framework v7.0.4
    - don't install illuminate/contracts v6.0.0|don't install laravel/framework v7.0.4
    - don't install illuminate/contracts v6.0.1|don't install laravel/framework v7.0.4
    - don't install illuminate/contracts v6.0.2|don't install laravel/framework v7.0.4

**Comment by GrahamCampbell** [comment]
You need to install v8, not v7.
