### ISSUE TITLE
Lower case 

### ISSUE THREAD

**Issue by murilolivorato** [vinkla/laravel-hashids#129]
hello ,I want to make lowercase .
I dont know what is happening 

```
FOLDER -
$code            = Hashids::connection('code')->encode(2);

 'code' => [
            'salt' => 'qwertyiopasdfghjkllzxcvbnm123456789',
            'length' => 8,
        ],

```
It is like this the result -

```
xpoNeP90
````

with some words uppercase . how could I make it all lowercase ? thanks

**Comment by vinkla** [comment]
Try changing the `alphabet` instead of the salt: https://github.com/vinkla/hashids#using-a-custom-alphabet
