### ISSUE TITLE
Decode not working

### ISSUE THREAD

**Issue by grsherwin** [vinkla/laravel-hashids#130]
The encode works great, but get this message when trying to decode....htmlspecialchars() expects parameter 1 to be string, array given
Code is this...
$hashids = Hashids::encode(1);
$numbers = Hashids::decode($hashids);

It also fails if I do this...
$hashids = Hashids::encode(1);
$numbers = Hashids::decode('JR');
with the same error message....
htmlspecialchars() expects parameter 1 to be string, array given

**Comment by GrahamCampbell** [comment]
This is correct. Decode returns an array. Please read the docs.
