### ISSUE TITLE
Local is working fine but on live i am getting error

### ISSUE THREAD

**Issue by javeedrahman** [vinkla/laravel-hashids#131]
I am getting following error

"message": "Argument 1 passed to GrahamCampbell\\Manager\\AbstractManager::makeConnection() must be of the type string, null given,

This is only one server.

Please help.

**Comment by vinkla** [comment]
If it works locally but not on your production server then it is probably an issue with your server.

**Comment by javeedrahman** [comment]
I have used this https://github.com/vinkla/hashids instead of laravel package.
