### ISSUE TITLE
Invalid phpdoc @method tags

### ISSUE THREAD

**Issue by kainxspirits** [vinkla/laravel-hashids#132]
Hi,

I saw on this commit https://github.com/vinkla/laravel-hashids/commit/21fe03dec5d78df8ea74cfbafa38b612725596f5#diff-5611343d13936e3b3de7f38f8318d4a3 that the docblocks have been changed. I'm not sure why, but it doesn't look like a valid phpdoc syntax and is causing errors with static analyzer (I use phpstan).

The old syntax `@method static string encode(mixed ...$numbers)` looked more suitable.

**Comment by vinkla** [comment]
Please submit a pull request with a fix.
