### ISSUE TITLE
Decoding always empty

### ISSUE THREAD

**Issue by jonitopsg** [vinkla/laravel-hashids#135]
"laravel/lumen-framework": "5.8.*"
 "vinkla/hashids": "6.0.0"

I made some modifications on hashids.php config file like this:

 'main' => [
       'salt' => 'F28F86043514AEB26943F1A67F21B94251201F322199855F1DF1B982E3CF7C92',
        'length' => '6',
         'alphabet' => 'abcdefghijklmnopqrstuvwxyz1234567890'
],

When i tried to decode Hashids::decode('34mm93'), it doesn't work. I have no response and the Lumen stops with "Illegal instruction: 4".

There's something wrong?

**Comment by vinkla** [comment]
Don't know how to solve your problem. Illegal instruction is probably not an issue with this library.
