### ISSUE TITLE
laravel 8 release ETA?

### ISSUE THREAD

**Issue by lsmith77** [vinkla/laravel-hashids#139]
seems like master has already been updated, any ETA for the next release? do you need feedback?

**Comment by GrahamCampbell** [comment]
It is already updated.

**Comment by lsmith77** [comment]
ah .. guess not tagged on github and so they "hide" the tag a bit .. sorry for the noise

![grafik](https://user-images.githubusercontent.com/300279/94283473-544d3000-ff51-11ea-8a50-0b6348edcc13.png)

**Comment by GrahamCampbell** [comment]
It is tagged, but not a "release". Releases don't matter though: they are GitHub concept. Nothing to do with the package being available on Packagist.

**Comment by lsmith77** [comment]
yeah .. I just didn't look carefully enough and so the github UI made believe 7.0 was the latest release. doh!

**Comment by GrahamCampbell** [comment]
This is really a GitHub UI problem.
