### ISSUE TITLE
Generating Case Sensative

### ISSUE THREAD

**Issue by onlinecheckwriter** [vinkla/laravel-hashids#142]
M2mzeJ3q**l**Rj8ENb
M2mzeJ3q**L**Rj8ENb

RJ6qGA6d**z**1eE1rD 
RJ6qGA6d**Z**1eE1rD

zRNXG06M**V**LjLxyB   
zRNXG06M**v**LjLxyB

They are two different value but in database it is same. Is there anyway to prevent it.  can we encode with all big caps or small cap or something...

**Comment by vinkla** [comment]
I would recommend not to store these in the database.

https://github.com/vinkla/hashids/issues/10#issuecomment-35918172
