### ISSUE TITLE
Adding Laravel 8 broke Laravel 7. Can you support both versions?

### ISSUE THREAD

**Issue by craftyshaun** [vinkla/laravel-hashids#144]
Hi.

I want to use this package in production where we are still using Laravel 7.X. I understand we should upgrade but sometimes there are other dependencies at play as this is a complex ERP system.

In commit ed2a1df8b94c5eea18fdf34620dff1c61b2bad09 to support Laravel 8 (#137) the 7.0 version was excluded from composer.

I'd like to propose updating the composer to support both versions as well as PHP 7.4:
```json
"require": {
        "php": "^7.3",
        "graham-campbell/manager": "^4.4",
        "hashids/hashids": "^4.0",
        "illuminate/contracts": "^7.0 || ^8.0",
        "illuminate/support": "^7.0 || ^8.0"
    },	  
```

From what I can see the code doesn't require anything fancy from the 8.0 release of Laravel.

I understand there is overhead in supporting older versions of Laravel however I'd appreciate your consideration.

Thanks

**Comment by vinkla** [comment]
Thanks for the suggestion Shaun. Not currently planing on supporting multiple versions of Laravel. You can still use this package with Laravel 7 if you install version 8.1.0.
