### ISSUE TITLE
Wrong return type of Facade methods

### ISSUE THREAD

**Issue by dpetrovaliev** [vinkla/laravel-hashids#147]
Hi, I'm using 8.1.0 version of your package and just spotted that the return types of these methods are wrong:
https://github.com/vinkla/laravel-hashids/blob/8.1.0/src/Facades/Hashids.php

I've seen that this is fixed in 9.X versions. Are you planing a release of a minor fix of this for 8.X version?

**Comment by vinkla** [comment]
> Are you planing a release of a minor fix of this for 8.X version?

There are no plans on releasing a fix for version 8. I suggest you update to version 9.
