### ISSUE TITLE
Add Laravel 7.x Support

### ISSUE THREAD

**Issue by ratatatKE** [vinkla/laravel-hashids#152]
Current version of Hashids requires `Illuminate/Support ^6.0` which is satisfiable by `illuminate/support[v6.0.0, ..., 6.x-dev]`. When trying to upgrade to Laravel 7.x, the framework will overwrite` illuminate/support` version 6 and therefore cannot coexist with it.

This causes problems for users who are trying to upgrade from Laravel 6.x to Laravel 7.x as captured in the below screenshot.

![Bildschirmfoto 2021-09-14 um 21 36 10](https://user-images.githubusercontent.com/8273966/133314676-f05f6308-9968-4967-ad82-6e2a301d2a73.png)

**Comment by vinkla** [comment]
Both Laravel 7 and 8 support is available. You'll need to install the correct version of this library. See the releases tab and compare versions.

**Comment by ratatatKE** [comment]
Please link us to the correct version of hashids. Under [`vinkla/hashids`](https://github.com/vinkla/hashids/releases) the releases tab only has up to version 4.1.0.

This is pretty confusing as am looking for a version 7 and above that supports laravel 7 in accordance with the error I shared in the earlier screenshot.

![Bildschirmfoto 2021-09-15 um 19 35 23](https://user-images.githubusercontent.com/8273966/133474039-b4f9a70b-4c6c-4c20-b89e-5f8f865515c1.png)

**Comment by vinkla** [comment]
https://github.com/vinkla/laravel-hashids/compare/7.0.0...8.0.0
