### ISSUE TITLE
Length of the generated ids

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [vinkla/laravel-hashids#153]
Hi, I would like to know if there is an estimate of how long the resulting ID would be

I mean, since it's guarantee that there will be no collision, then the length of the generated ID must be infinite, but let's say that I encrypt numbers up to 40k, is there a guarantee that the resulting ids won't be longer than N letters?

**Comment by vinkla** [comment]
https://github.com/vinkla/hashids/issues/134
https://github.com/vinkla/hashids/issues/74
