### ISSUE TITLE
Unsupported operand types: int - string

### ISSUE THREAD

**Issue by Beckhem1998** [vinkla/laravel-hashids#159]
Getting this issue when trying to encode ID of a model which is int, laravel version 9.3.1 and PHP 8.0

**Comment by vinkla** [comment]
Please submit a failing test case using a pull request.

**Comment by Beckhem1998** [comment]
@SirAddam I just required this package ["hashids/hashids"](https://packagist.org/packages/hashids/hashids) and got it working
