### ISSUE TITLE
Regarding the behavior in the environment of PHP 8.0 and Laravel 6.

### ISSUE THREAD

**Issue by SardineTa23** [vinkla/laravel-hashids#160]
Hello,

I am currently in charge of upgrading the PHP version of my own application (7.3 -> 8.0).

Laravel supports PHP8.0 in v6.20.44, but V7.0.0 of this great package (laravel-hashids) does not work in a PHP8.0 environment.

```
$ composer require vinkla/hashids:7.0.0
./composer.json has been updated
Running composer update vinkla/hashids
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires vinkla/hashids 7.0.0 -> satisfiable by vinkla/hashids[7.0.0].
    - vinkla/hashids 7.0.0 requires php ^7.2 -> your php version (8.0.13) does not satisfy that requirement.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

The "hashids v9.1.0" which supports PHP 8.0 requires Laravel version 8 or higher.

Can I create a Pull Request (e.g. v7.1.0) modified to support PHP8.0?

I am not good at English, so I apologize if what I am trying to say is not clear.

Thank you!

**Comment by vinkla** [comment]
No, sorry, we only maintain the latest Laravel version.

**Comment by SardineTa23** [comment]
OK, thank you!
