### ISSUE TITLE
Type error after v11 update

### ISSUE THREAD

**Issue by nashsaint** [vinkla/laravel-hashids#182]
Upgraded Laravel to 10 and this repo to v11 encode method throws this error

`Hashids::encode(1)`

error:
`Hashids\Hashids::__construct(): Argument #2 ($minHashLength) must be of type int, string given`

**Comment by nashsaint** [comment]
So, changing the config `length` from
`'length' => env('HASH_LENGTH',50)`
to this
`'length' => 50`
works

despite having this on the env `HASH_LENGTH=50`

**Comment by vinkla** [comment]
Please provide a failing test case in a pull request.
