### ISSUE TITLE
Are you using multiple connections?

### ISSUE THREAD

**Issue by vinkla** [vinkla/laravel-hashids#184]
We are currently considering the [future of the Hashids project](https://github.com/sqids/sqids-php). The Laravel integration allows you to have multiple configurations for Hashids. Personally, I rarely use this feature and believe it can confuse new users of the package. 

We want to know how you use this library; do you use multiple alphabets in your Laravel project?

**Comment by Plytas** [comment]
We do use different connections for different models. I cannot tell if there's a good reason for that, but it gives a peace of mind to have things separated.

**Comment by MordiSacks** [comment]
I use different connection for each model
