### ISSUE TITLE
Getting Duplicate Hash IDs

### ISSUE THREAD

**Issue by jakelehner** [vinkla/laravel-hashids#191]
Howdy.

So I'm dealing with a fun issue now involving Hash IDs and the Laravel JSON:API package ... in that it turns out they are not unique. Like. at all. Wondering if you have any input on this.

* We use Hash IDs configured [per the Laravel JSON:API docs](https://laraveljsonapi.io/docs/1.0/schemas/identifier.html#hash-ids)
* We use a 32 character salt and ID length of 12
* Results vary based on the salt, but in our production system we are getting collisions on int IDs as low as 52!!
  * 52 and 1196 have the same Hash ID
  * 54 and 1110 have the same Hash ID
  * 56 and 156 ...
* We use a long length ID as well using the same salt and a 32 character ID.
  * Same results from different int IDs
  * 
Clearly the issue here is when you decode the hash, it only decodes to only ONE of the original int values.

As you can imagine, we're in a bit of a pickle on this one. 

Have any thoughts on this? Both with what's happening and any suggestions for a fix?

**Comment by jakelehner** [comment]
False alarm with how the data was being queried.

**Comment by ianhawes** [comment]
@jakelehner Could you clarify what the false alarm was? My guess is that you were storing them somewhere and then re-querying but the query was not case sensitive?
