### ISSUE TITLE
Only returning characters and not numbers (mix)

### ISSUE THREAD

**Issue by KayTokyo** [vinkla/laravel-hashids#33]
Hey i just tried this package on Laravel 5.2 but its giving me back just characters and not numbers and characters.

Config File:
```
<?php
return [

    'default' => 'main',

    'connections' => [

        'main' => [
            'salt' => env('APP_KEY'),
            'length' => 8,
            'alphabet' => 'abcdefghijklmnopqrstuvwxyz',
        ],

        'alternative' => [
            'salt' => 'your-salt-string',
            'length' => 'your-length-integer',
            'alphabet' => 'your-alphabet-string',
        ],

    ],

];

```

Route File:

```
<?php

use App\User;

Route::get('/test', function () {

	return Hashids::encode(12);
});
```

Output

```
reazwdkw
```

**Comment by vinkla** [comment]
Please share more of your code.

**Comment by GrahamCampbell** [comment]
Did you remember to run `php artisan config:cache`?

**Comment by KayTokyo** [comment]
@vinkla 

Hey,

Ive added a little more to my initial comment. But theres nothing else to show. Im just trying to encode a integer in my route file and return. It's being returned but im only receiving characters and not numbers.

**Comment by vinkla** [comment]
Then it is working as expected. You've to add numbers to your alphabet in order to display numbers. Try replacing `abcdefghijklmnopqrstuvwxyz` with `abcdefghijklmnopqrstuvwxyz0123456789`.

**Comment by KayTokyo** [comment]
@vinkla 

I just tried that and im still only getting letters
