### ISSUE TITLE
Hashids::decode should return integer instead of array

### ISSUE THREAD

**Issue by mehrdaad** [vinkla/laravel-hashids#35]
Maybe I'm missing something but shouldn't ``decode`` method return a single integer instead of an array, since hash is considered to be unique?

**Comment by vinkla** [comment]
This is expected behaviour. I know that isn't super clear but that is how the Hashids library work.

**Comment by mehrdaad** [comment]
But aren't hashes supposed to be unique?then why arrays?

**Comment by vinkla** [comment]
They are unique? You can fetch the first index `[0]` which is the encoded string.

**Comment by mehrdaad** [comment]
@vinkla I'm sorry are you asking the same question I asked you from you? Is there any reason that they are provided in an array?

**Comment by vinkla** [comment]
@mehrdaad yeah, to be consistent. If you encode an array of ids then you want those returned in the same way as when you encoded them.

**Comment by nicgutierrez** [comment]
here's my two cents: I think that if you provide one string, you should get one string back. If you provide with an array, an array of decoded values is what you should get. I agree with @mehrdaad here. 

Other than that, great job @vinkla, I've been using this projects for a while ;)

**Comment by vinkla** [comment]
Yeah, we've actually discussed this in the Hashids organization and we want to keep this behavior consistent through out all languages and libraries. 

Though, we are looking into new ways of handling this in future versions of Hashids since we get asked about this a lot. 

I'm glad you like it :smile:
