### ISSUE TITLE
Getting this error `bcdiv` while encoding the ID's

### ISSUE THREAD

**Issue by Mahmoudz** [vinkla/laravel-hashids#37]
```
{"message":"Call to undefined function Hashids\\bcdiv()","status_code":500}
```

I am on PHP 7.0.9.

It seems like my server is missing `php-bcmath`!

**Comment by vinkla** [comment]
Try installing the `php-bcmath` extension?

**Comment by Mahmoudz** [comment]
I just solved it, I had some local troubles with my environment.. Thanks @vinkla

**Comment by melzareix** [comment]
How did you solve this? We use laradock and have the same problem although `php-bcmath` is installed and working outside `hashids`
