### ISSUE TITLE
Problem with laravel 5.1.45

### ISSUE THREAD

**Issue by gdg87** [vinkla/laravel-hashids#38]
I tried to install the package on a fresh laravel 5.1.45 installation and have this error:

`Problem 1
    - Installation request for vinkla/hashids ^3.0 -> satisfiable by vinkla/hashids[3.0.0].
    - Conclusion: remove laravel/framework v5.1.45
    - Conclusion: don't install laravel/framework v5.1.45
    - vinkla/hashids 3.0.0 requires illuminate/contracts 5.2.* || 5.3.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/contracts v5.2.0|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.19|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.21|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.24|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.25|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.26|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.27|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.28|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.31|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.32|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.37|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.43|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.45|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.6|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.2.7|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.3.0|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.3.16|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.3.23|don't install laravel/framework v5.1.45
    - don't install illuminate/contracts v5.3.4|don't install laravel/framework v5.1.45
    - Installation request for laravel/framework (locked at v5.1.45, required as 5.1.*) -> satisfiable by laravel/framework[v5.1.45].`

**Comment by vinkla** [comment]
Version 3.0.0 doesn't support Laravel 5.1. I suggest you [upgrade your Laravel application](https://laravel.com/docs/5.3/upgrade#upgrade-5.2.0) or use version 2 of this package.
