### ISSUE TITLE
use in lumen

### ISSUE THREAD

**Issue by sajadpm** [vinkla/laravel-hashids#39]
hi , i cant used package in lumen . can help me ?

**Comment by vinkla** [comment]
Yes you can.

**Comment by sajadpm** [comment]
i cant found config file . hashid.php , I do not know where config hashid ?

**Comment by vinkla** [comment]
You've to copy/paste the config file yourself since you're using Lumen.

**Comment by sajadpm** [comment]
added package lumen project and uncomment $app->withFacades(); in bootsrap/app.php . 
and added 
$app->register('Vinkla\Hashids\HashidsServiceProvider');
class_alias('Vinkla\Hashids\Facades\Hashids', 'Hashids');
in bootsrap/app.php  . 

now how to add config 
            'salt' => 'your-salt-string',
            'length' => 'your-length-integer',
            'alphabet' => 'your-alphabet-string'
in lumen project ? where added ?

**Comment by vinkla** [comment]
I'm sorry, I do not understand what you're asking?

**Comment by sajadpm** [comment]
sory for my bad en language , I do not know set config length or alphabet in lumen .

**Comment by sajadpm** [comment]
Not somebody help me?

**Comment by vinkla** [comment]
Did you copy and paste the config file into your project?

**Comment by sajadpm** [comment]
my project is lumen And there is no configuration folder . where is paste file ? Do you have an example lumen project ?

**Comment by vinkla** [comment]
If you are new to the Laravel framework I suggest using Laravel instead of Lumen.

**Comment by vinkla** [comment]
If you need this library, why are you using Lumen instead of Laravel?

**Comment by sajadpm** [comment]
I'm using because I lumen mobile API for writing

**Comment by vinkla** [comment]
What do you mean? Laravel and Lumen is basically the same framework.

**Comment by sajadpm** [comment]
According to the reference : 
http://stackoverflow.com/questions/29647960/differences-and-similarities-between-lumen-and-laravel
Lumen represents a shift on slimming Lumen to focus solely on serving stateless, JSON APIs. As such, sessions and views are no longer included with the framework. If you need access to these features, you should use the full Laravel framework.

**Comment by vinkla** [comment]
Yeah, but since you're struggling with Lumen wouldn't it be easier if you use Laravel?

**Comment by mustafalim** [comment]
Hi, I think you can try this:
1. Copy vendor/vinkla/hashids/config/hashids.php to config/hashids.php
2. Add this line to bootstrap/app.php 
$app->configure('hashids');
