### ISSUE TITLE
Weird problems to decode/encode

### ISSUE THREAD

**Issue by Albvadi** [vinkla/laravel-hashids#40]
Hi,
I´m encountering problems to encode/decode the ids of my models. It´s a lot of weird, because it doesn´t always happen.

I have a few screens to explain my problem:

1. I create a new document and check in the select, all the id's are encode:
![1](https://cloud.githubusercontent.com/assets/6285255/21651554/56aaf43c-d2a9-11e6-8302-88517487afab.png)

1. When I submit the document, the decode fails:
![2](https://cloud.githubusercontent.com/assets/6285255/21651593/7cb51b26-d2a9-11e6-9b6e-04019f434185.png)

1. I go back, refresh the page, and the id´s are corrupt:
![3](https://cloud.githubusercontent.com/assets/6285255/21651631/a9d48402-d2a9-11e6-88cb-ea9bf37e4591.png)

1. Finally, go to dashboard, go again to create document, check the id´s encode (same as image 1) and now, the decode works well:
![4](https://cloud.githubusercontent.com/assets/6285255/21651663/cad0e25e-d2a9-11e6-911a-4801217db6a7.png)

I don´t know what it´s happening....
This is all my config and uses:

- config/hashids.php
```php
'default' => 'main',
'connections' => [

        'main' => [
            'salt' => 'my-password-secret',
            'length' => '12',
            'alphabet' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890',
        ],

        'alternative' => [
            'salt' => 'your-salt-string',
            'length' => 'your-length-integer',
            'alphabet' => 'your-alphabet-string',
        ],

    ],
```

- DocumentController (create method)
```php
public function create()
    {
            $users = User::select(['id', 'name'])->get();
            foreach ($users as $user) {
                $owners[Hashids::encode($user->id)] = $user->name;
            } 
            
            return view('documents.create', ['owners' => $owners]);                       
    }
```

- Document form view
```blade
{{ Form::select('user_id', $owners, null, ['class' => 'form-control']) }}
```

- Document Store
```php
public function store(DocumentStore $request)
{
    dump($request->all());
    dump(Hashids::decode($request->user_id));
    $user_id = Hashids::decode($request->user_id)[0];

    $document = new Document();
    $document->fill($request->all());
    $document->user_id = $user_id;

    $document->save();

    return redirect()->route('documents.index')->with('message', 'Successfully created Document!');
}
```
Sorry for the long issue and thanks!!

**Comment by vinkla** [comment]
> When I submit the document, the decode fails:

Please show me the line 64.

**Comment by Albvadi** [comment]
- Line 65 (In the last portion of code of the explanation)
```php
$user_id = Hashids::decode($request->user_id)[0];
```

**Comment by vinkla** [comment]
Please share the result from `dd(Hashids::decode($request->user_id));`.

**Comment by Albvadi** [comment]
You can view the result in the screenshots.
In the screenshot 2, the result of `dump(Hashids::decode($request->user_id));` it´s an empty array, under the request array.
In the screenshot 4, the result of `dump(Hashids::decode($request->user_id));` it´s an array wich contains 3, the real id of the user.

In both cases, decode the same string `d9GWyvO0KOeg`, but first fails and second not. And between both cases, in a refresh of the page, the user_ids are corrupt (seen in screenshot 3).

Sorry if you don´t understand all, my english itsn´t very good...  :sweat:

**Comment by vinkla** [comment]
Don't worry. The thing is, I do not see anything wrong with your code. Please share the output I asked for.

**Comment by Albvadi** [comment]
The output it´s:
```php
array:1 [▼
  0 => 3
]
```
I´m trying now, but now works all times.. It´s very strange, I don´t see anything worng in the code and I don´t find a pattern that causes failures... :(

**Comment by vinkla** [comment]
Did you manage to solve this?

**Comment by Albvadi** [comment]
I´ll try another approach. If this doesn´t work, I´ll try manually obfuscation of the id or use another library..

Thanks anyway for your help reviewing the code..

**Comment by mathewparet** [comment]
I have a similar issue. Encoding decoding works on my laptop. But doesn't seem to work on the server. For testing purposes I used the same salt, length, and alphabets on both my laptop and the server.

decode seems to return an empty array on the server.

Interesting thing is that it works in one part of the code, and doesn't work on another. Both use the same code to decode the hashid.
