### ISSUE TITLE
any tips on how to correctly set salt/lenght?

### ISSUE THREAD

**Issue by huglester** [vinkla/laravel-hashids#41]
Hello

do you have any tips on how is to safety generate the 'salt'? 

Thank you

**Comment by GrahamCampbell** [comment]
Just use laravel's str_random to generate it, or whatever. TBH, hash ids arn't "secure", anyway, so you might as well just write a human readable name for the salt.

**Comment by huglester** [comment]
thanks for explaining. thought it is more problems :)
