### ISSUE TITLE
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'parse error, expecting `';'' or `'{''' in /vendor/vinkla/hashids/src/HashidsServiceProvider.php:121

### ISSUE THREAD

**Issue by msonowal** [vinkla/laravel-hashids#42]
I get this error on log whenever some commands are running in laravel,
the application is working as expected but in log it is getting created as soon as there is command fires

**Comment by vinkla** [comment]
How is this related to this package? If you want our help you need to provide a better description of your issue.

**Comment by msonowal** [comment]
It is related to to the package cause it's coming as `HashidsServiceProvider.php:121`
To get the similar situation
Install laravel > install hashids > schedule some custom command on Kernal and run every minute,
and you see this error on the log

**Comment by rmkelly** [comment]
I also get this error with PHP 7.1 and Laravel 5.4.

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in vendor\vinkla\hashids\src\HashidsServiceProvider.php:121

The error presents itself when calling Hashids::encode

**Comment by msonowal** [comment]
@vinkla  see the error other people are also saying and how can you ask that it is not related to your package the error stack clearly says that it is coming,
my project on php 7.0 with ubuntu 16.04 laravel 5.3 , the error stays in logs whenever ca console commands are executed or sometime in request also

**Comment by vinkla** [comment]
It looks like you guys are running old versions of PHP. The test suite still passes on both 7.0 and 7.1. Please provide a failing Travis test.

**Comment by msonowal** [comment]
No it's updated with latest minor 7.0.*

**Comment by loranger** [comment]
Same issue here, with Laravel 5.4, PHP 7.0.15 and hashids ^3.1

```
[2017-03-08 10:01:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'parse error, expecting `';'' or `'{''' in /Users/loranger/Developer/myproject/vendor/vinkla/hashids/src/HashidsServiceProvider.php:121
```

As @msonowal [said](https://github.com/vinkla/laravel-hashids/issues/42#issuecomment-274236390) the Exception is thrown only when Hashids facade is called by a scheduled task.
Within the web app everything works flawlessly

**Comment by vinkla** [comment]
@loranger @msonowal @rmkelly could you please share the output of `php -v` and paste it here?

Here is an example of that the output should look like; 

```sh
PHP 7.1.2 (cli) (built: Feb 17 2017 10:52:17) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by loranger** [comment]
Sure, here is mine :

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 22 2017 08:51:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by vinkla** [comment]
@loranger could you also share your entire exception stack trace?

**Comment by loranger** [comment]
Ok, I found what was my problem.
@vinkla was right : It was a PHP version issue.

My supervisord task was using the following command :

```ini
command=php /Users/loranger/Developer/myproject/artisan queue:work --sleep=3 --tries=3 --daemon
```

But supervisord does not use the same $PATH as I do, and was falling back on the PHP version installed with OSX (5.6.28)

I fixed this by specifying the full PHP 7 binary path :

```ini
command=/usr/local/bin/php /Users/loranger/Developer/myproject/artisan queue:work --sleep=3 --tries=3 --daemon
```

And now everything works fine.
I hope you guys will find a solution for your issue. Maybe something similar as mine.

@vinkla, unfortunately, my stack trace is (was) empty. 

I had thoses useless lines in my `laravel.log` :
```log
[2017-03-08 10:01:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'parse error, expecting `';'' or `'{''' in /Users/loranger/Developer/myproject/vendor/vinkla/hashids/src/HashidsServiceProvider.php:121
Stack trace:
#0 {main}
[2017-03-08 10:01:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'parse error, expecting `';'' or `'{''' in /Users/loranger/Developer/myproject/vendor/vinkla/hashids/src/HashidsServiceProvider.php:121
Stack trace:
#0 {main}
[2017-03-08 10:01:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'parse error, expecting `';'' or `'{''' in /Users/loranger/Developer/myproject/vendor/vinkla/hashids/src/HashidsServiceProvider.php:121
Stack trace:
#0 {main}
```

and fewer in my `supervisor/worker.log` :
```log
  [Symfony\Component\Debug\Exception\FatalErrorException]
  parse error, expecting `';'' or `'{''



  [Symfony\Component\Debug\Exception\FatalErrorException]
  parse error, expecting `';'' or `'{''



  [Symfony\Component\Debug\Exception\FatalErrorException]
  parse error, expecting `';'' or `'{''
```

Anyway, thank you so much for this package and your support ! 👍

**Comment by msonowal** [comment]
@vinkla as you asked still a noobish question here is the output
`PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies`
and as I already said the errors appear on logs if there are schedule tasks configured on the laravel app, I am using laravel 5.4 and scheduled some commands which runs every 5 minutes, and it shows in the log

**Comment by vinkla** [comment]
@msonowal you need to practice your manner. You won't get any more help from me. Ever.
