### ISSUE TITLE
Laravel 5.4 support broken

### ISSUE THREAD

**Issue by andkom** [vinkla/laravel-hashids#43]
Hello!

In laravel 5.3 i had custom connections with custom alphabet "0123456789abcdef"
Since the new version of hashids has alphabet length check, i must stay on prev version 2.4 which doesn't allow me to update it to laravel 5.4:

> vinkla/hashids 2.4.0 requires illuminate/support 5.1.* || 5.2.* || 5.3.*

**Comment by vinkla** [comment]
We bumped the package with a major version with the new changes in Hashids. Don't plan to release a new 2.* version right now. Sorry.
