### ISSUE TITLE
 PHP 5.6 support dropped

### ISSUE THREAD

**Issue by fntneves** [vinkla/laravel-hashids#46]
The new release adds support for Laravel 5.4 and removes support for PHP 5.6.

However, the minimum supported PHP version in Laravel is 5.6.4 So, people who use PHP 5.6 are not able to use Hashids.

Wouldn't it be better to keep support for PHP 5.6 ?

**Comment by vinkla** [comment]
Laravel 5.5 will most likely move to PHP 7.0 (probably in June or July 2017). We're just one step ahead in the release. I suggest upgrading to PHP 7.0+ since there are huge benefits.

**Comment by fntneves** [comment]
I totally agree with you! However, since this  is a package for Laravel, I think it should support the same versions per release. This is just a suggestion, to keep support for PHP 5.6 until the next LTS release of Laravel.

**Comment by vinkla** [comment]
I get your point but I wanted to benefit from new changes in PHP 7.0 and decided to drop 5.6 from all my packages.

**Comment by fntneves** [comment]
Ok, no problem.
Keep the good work, thanks for replying 👍
