### ISSUE TITLE
How i get a minimum hashid size using this?

### ISSUE THREAD

**Issue by strikermdd** [vinkla/laravel-hashids#47]
Hello, how i get a minimum hashid size using this?

I see that hashids has a option for this (padding), but i don´t see a "native" option in this bridge. Its possible?

**Comment by GrahamCampbell** [comment]
Yes. https://github.com/vinkla/laravel-hashids/blob/master/config/hashids.php#L44

**Comment by GrahamCampbell** [comment]
That will set a minimum hashid size.
