### ISSUE TITLE
minHashLength

### ISSUE THREAD

**Issue by kezangwangmo** [vinkla/laravel-hashids#49]
@vinkla how to define minimum hash length?

**Comment by vinkla** [comment]
In the config file.

**Comment by kezangwangmo** [comment]
![hashids](https://cloud.githubusercontent.com/assets/18734060/24286319/e113074e-109e-11e7-8dd7-3d6610264b07.JPG)

I have specified the length to 10, but generated hash remains the same.

**Comment by vinkla** [comment]
> I have specified the length to 10, but generated hash remains the same.

Show me example hashes before and after you change the number.

**Comment by kezangwangmo** [comment]
![hash](https://cloud.githubusercontent.com/assets/18734060/24286625/2a79ca16-10a0-11e7-94e8-fa3455833323.JPG)

This is the result when encoding "1008" despite specifying the length to 10.

**Comment by vinkla** [comment]
Did you clear the Laravel config cache?

**Comment by kezangwangmo** [comment]
@vinkla it worked ! Thanks 👍
