### ISSUE TITLE
Return string from decode

### ISSUE THREAD

**Issue by strikermdd** [vinkla/laravel-hashids#50]
I´m trying to return the id of the element using -> $id = Hashids::decode($uuid);

But, it returns me a array of one element. Its possible to return only the "id" value from the decode? "example: '10' "

**Comment by vinkla** [comment]
Yes, this is expected behavior. Fetch the first item in the array.

**Comment by GrahamCampbell** [comment]
Here's a real world example for you:

![image](https://cloud.githubusercontent.com/assets/2829600/24759981/1d1f38d0-1adf-11e7-9ad2-de23c2581902.png)
