### ISSUE TITLE
Create HashIds validator

### ISSUE THREAD

**Issue by DeftNerd** [vinkla/laravel-hashids#52]
Being able to extend the Laravel validator to check hashids would be helpful to check for validity on POSTs

`    $this->validate($request, [`
`        'hashid' => 'required|hashids',`
`        'title' => 'required|unique:posts|max:255',`
`        'body' => 'required',`
`    ]);`

Info on creating custom validation rules [can be found here. ](https://laravel.com/docs/master/validation#custom-validation-rules)

I'm personally doing it this way but I'm sure there's a more optimal method
```
        Validator::extend('hashid', function ($attribute, $value, $parameters, $validator) {
            if (is_array($value)) {
                foreach ($value as $item) {
                    if (!is_int(array_first(\Vinkla\Hashids\Facades\Hashids::decode($item)))) {
                        return false;
                    }
                }
            } else {
                if (!is_int(array_first(\Vinkla\Hashids\Facades\Hashids::decode($value)))) {
                    return false;
                }
            }
            return true;
        });        
```

**Comment by vinkla** [comment]
Thanks for you suggestion! Though, I wont merge any custom validation tool into this package at the current time. We'll leave this part to the application artisans.
