### ISSUE TITLE
HashidsServiceProvider.php line 121: syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by djave-co** [vinkla/laravel-hashids#53]
There is an extra 

    : array

on the end of line 121 in HashidsServiceProvider.php which is breaking the package.

**Comment by vinkla** [comment]
Yes, this is correct. [This is called return types in PHP.](https://secure.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) You need to install PHP 7.0+ in order to use this package.

**Comment by GrahamCampbell** [comment]
@vinkla I think the point is that is is a breaking change if you were extending the service provider.

Perhaps you should mark service providers as `@internal` if you want to exclude them from the BC promise?

---

Raising the min version of php is not breaking, but making breaking changes to the signature of public or protected methods, is breaking.

**Comment by vinkla** [comment]
> Raising the min version of php is not breaking, but making breaking changes to the signature of public or protected methods, is breaking.

I see your point but I think it is fine the way it is.
