### ISSUE TITLE
Does not support encoding anything except numbers?

### ISSUE THREAD

**Issue by banqhsia** [vinkla/laravel-hashids#55]
Hi, I'm using `hashids` and would like to hash MongoDB generated `_id` (ObjectID).

They seems like `59075c853bacf0e02965c690`.
Yes, it's not friendly to url.

However, I got fail when trying to encode such an ID like this, 

    Hashids::encode('59075c853bacf0e02965c690');

Got empty string `""` eventually.

Not only `ObjectID`, but anything except number, will get empty string too.

How can I deal with a string or it just support numbers?

Thank you so much :)

**Comment by vinkla** [comment]
Please see the MongoDB section in [Hashids documentation](https://github.com/ivanakimov/hashids.php#more-options).
