### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by nospoon** [vinkla/laravel-hashids#56]
Why has the support for 5.6 been dropped? 5.6 has not reached end-of-life just yet and it will prevent a lot of people from using the package.

**Comment by GrahamCampbell** [comment]
It doesn't prevent people using the package. They can just use older versions. They seem to be fine with using older versions of php, so.

**Comment by nospoon** [comment]
Laravel 5.4 is not supported on earlier versions.

**Comment by GrahamCampbell** [comment]
Well either use an older version of laravel, or upgrade php.

**Comment by vinkla** [comment]
We wanted to benefit from new changes in PHP 7.0 and decided to drop 5.6 from all our packages.
