### ISSUE TITLE
Please support Laravel 5.5 

### ISSUE THREAD

**Issue by DesmondPang** [vinkla/laravel-hashids#60]
I found that you have already updated requirement to php 7+ and supported Auto-Discovery. However, the the version of  Laravel is 5.3.*. I am testing Laravel 5.5 dev version. It is possible to support it? Thanks.

**Comment by vinkla** [comment]
> It is possible to support it?

Yes, we plan to support it. Though, Laravel 5.5 is probably at least a month away. As soon as there are new versions of [`graham-campbell/manager`](https://github.com/GrahamCampbell/Laravel-Manager) and [`graham-campbell/testbench`](https://github.com/GrahamCampbell/Laravel-TestBench) available I will start working on 5.5 support.

**Comment by vinkla** [comment]
Added in version 3.2.0.
