### ISSUE TITLE
Segmentation fault: 11 when encoding small numbers

### ISSUE THREAD

**Issue by MrTeapot** [vinkla/laravel-hashids#61]
Hey!

I am running this in a laravel database seeder and using Hashids::encode($todo->id) gives me Segmentation fault: 11 in the console when I seed the database.

However, if I add a big enough number to the ID it works, for example, Hashids::encode($todo->id + 100) works fine.

Can anyone explain why this is happening? I'd rather not add 100 to every ID

Thanks in advance

/Teapot

**Comment by vinkla** [comment]
What version of this package and Laravel are you using? What is the value of `$todo->id`?

**Comment by MrTeapot** [comment]
"php": ">=7.1.4",
"laravel/framework": "5.4.*",
"vinkla/hashids": "^3.1"

**Comment by vinkla** [comment]
I'm running those versions and I'm not getting this error. Segmentation fault errors are very hard to debug. There are tests which prove that the [Hashids library work as it should](https://github.com/ivanakimov/hashids.php/blob/899a837a35a1da28550a48886e3ba008ede8d9f0/tests/HashidsTest.php#L174). My guess is that this is something in your environment.

**Comment by MrTeapot** [comment]
I bring good news and bad news. 
Good news: it works now!
Bad news: I'm not sure why it suddenly works. I messed a lot with php and homebrew, ran some commands. One even took 8min(!). So it was definitely something with my environment.

Anyway, great package and thanks a lot for your quick response! <3
