### ISSUE TITLE
Consider removing random config/hashids.php settings

### ISSUE THREAD

**Issue by wjgilmore** [vinkla/laravel-hashids#66]
Hi,

We love the package, and use it in a rather high traffic REST API. I'll admit what I'm about to explain is a corner case, albeit one that burned us bad, and so I'd like to make a suggestion for a minor but important change.

We're running two production projects, a REST API and a legacy MVC web application. We upgraded the web application to Laravel 5.4, and in doing so learned the version of this package we were running only supported versions of Laravel 5.3 and earlier. However upon upgrading we learned the latest version only supported PHP 7. Because we're still running PHP 5.6, we concluded the practical solution would be to simply use the hashids/hashids package directly in the web application.

Due to legacy reasons our REST API just so happens to pass an encoded string over to the web application, meaning strings encoded by vinkla/hashids would be decoded by hashids/hashids. No big deal since vinkla/hashids ultimately relies upon hashids/hashids to do the encoding/decoding.

Even so, obviously out of paranoia we confirmed both packages were encoding and decoding the same strings in identical fashion. However just this morning I suddenly noticed this was no longer the case, and hashids/hashids was no longer able to decode strings encoded by vinkla/hashids.

This is a pretty big deal (to us), and so I scrambled to figure out what changed. Finally it dawned on me that at some point somebody published the vendor config packages to `config/`, and in doing so the `config/hashids.php` file which was generated actually overrode the default empty salt, 0 length, and empty alphabet configuration settings defined in `HashidsFactory.php`, using these instead:

```
'main' => [
'salt' => 'aw00ga%(45$#',
'length' => '15',
'alphabet' => 'abcdefghijklmnopqrstuvwxyz0123456789',
],
```

After returning these settings to the defaults, everything started working again. Therefore long story short, I'd like to suggest the default `config/hashids.php` file simply define `main` like so, therefore leaving it to the user to define these as desired:

```
'main' => [
'salt' => '',
'length' => 0,
'alphabet' => '',
],
```

Thanks again for the great package!

**Comment by vinkla** [comment]
Hey @wjgilmore, I agree with you. This is a corner case. Also, the random configuration values you refer to were added by someone who is involved in building your application. Those values doesn't exist in this package.

https://github.com/vinkla/laravel-hashids/blob/052ee165751cb4dfcd2801d234e9e5835a1c0d56/config/hashids.php#L42-L45

I suggest you upgrade your application to Laravel 5.5 and PHP 7.0. In Laravel 5.5 [you get asked what packages](https://laravel-news.com/vendorpublish) you want to publish configuration files from. You'll also benefit from the speed and features of PHP 7.0.

**Comment by wjgilmore** [comment]
Great thank you for the clarification. Admittedly I am totally baffled by the appearance of config/hashids.php then, because there is just simply no way those values were manually entered by one of our team members. I don't doubt for a second the configuration files were published, but those values are are a real mystery. Thank you for responding with your thoughts, I really appreciate it!
