### ISSUE TITLE
Can not decode after upgrage PHP 7

### ISSUE THREAD

**Issue by oom-patchara** [vinkla/laravel-hashids#67]
This just happen to day after I upgrade PHP from 5.6 to 7.0 
The encode is working fine but decode seem to be a problem. Could you please guide me where should I look.

Thanks for the great package you have made.

**Comment by vinkla** [comment]
Please provide more information such as errors and values you are working with.

**Comment by oom-patchara** [comment]
Below is how I use your Hashids

In Model class I encode id by adding model new attribute:
```
namespace App;
use Illuminate\Database\Eloquent\Model;
use Vinkla\Hashids\Facades\Hashids;

class Workflow extends Model
{
    protected $appends = ['hashid'];
    public function getHashidAttribute()
    {
        return Hashids::encode($this->attributes['id']);
    }
```
I decode id in routes/web.php like so:
```
Route::get('workflow/{workflow}', 'MainController@show');
......
Route::bind('workflow', function($value, $route) {
	try {
	    $id = Hashids::connection('main')->decode($value)[0];
	    return $id;
    } catch (Exception $e) {
	    return abort(404);
	}
});

```
Then in MainController.php I can get decoded id as below code:
```
public function show($workflow_id)
{
        $wf = Workflow::where(['workflow_id', '=', $workflow_id])->get();
        return $wf;
 }
```
Again, This is working fine and start to have a problem yesterday since I did upgrade my local computer (Mac OSX) from PHP 5.6 to 7.0, there are working okay too on the Live server which already has PHP7.0. Obviously is not about PHP version but I just want to give you all details about when the problem start.

There is no error message return not any error log as well just "The connection was reset" in the browser. I found that the problem was in routes/web.php it can not decode the given encoded id ($value).

`$id = Hashids::connection('main')->decode($value)[0];`

But, when I debug and try to decode like this it's working:
```
Route::bind('workflow', function($value, $route) {
	try {
           $test = Hashids::encode(12);
	    $id = Hashids::connection('main')->decode($test)[0];
	    return $id;
    } catch (Exception $e) {
	    return abort(404);
	}
});
```
Your comments on this would be appreciated.

**Comment by vinkla** [comment]
Hmm, not sure what your issue is here. What versions of this package and Laravel are you using?

**Comment by oom-patchara** [comment]
I am using Laravel 5.3 and already update your package to 3.3.0 yesterday but doesn't help.

**Comment by vinkla** [comment]
> I am using Laravel 5.3 and already update your package to 3.3.0 yesterday but doesn't help.

The version 3.3.0 doesn't support Laravel 5.3. Try upgrading your Laravel application to 5.5.

**Comment by oom-patchara** [comment]
As Hashids required BCMath extension in order to work. Optional GMP extension. from here
[https://github.com/ivanakimov/hashids.php](url)

Hope this could help other people who install PHP7.x from https://php-osx.liip.ch same myself.
Tis php-osx come with both BCMatch and GMP extensions. So after remove GMP everything working perfect as it was before.

Thank you @vinkla for the good package and support

**Comment by niiapa** [comment]
@oom-patchara I want to try this removing GMP thing (I don't even know if I have it and it's causing issues), but my problem in my issue also stems from decoding problems although I narrowed it down further.

Perhaps it's related. I've searched on how to remove the extensions but no luck. I'm running OS X as well and php 7.1. 

Thanks.
