### ISSUE TITLE
Hashids causing server crash

### ISSUE THREAD

**Issue by niiapa** [vinkla/laravel-hashids#69]
Hi. First off, thanks for the package. I've been using it for years. Recently, when Laravel 5.5 came I upgraded and migrated a project over to it. Everything doesn't work until it does and there's an odd roundabout way about this. Let me explain.

I'm using Laravel as a backend to a React JS frontend connected via the GraphQL Api...
The problem is, when I'm trying to encode some things, it causes my server to crash.

Per se... encoding the ID of a User model. `Hashids::encode($user->id)` will cause the server to crash(yes the ID exists when I `dd` it), unless I try and encode some random string first... `Hashids::encode('adsadadasd')`, make a request to the server, then comment out the random string encoding, then normal encoding will work again.

If I clear the cache, `php artisan cache:clear`, the problem returns. I have to encode a random made up string manually, make a request to the server, have it cache, then I can use the same old code as before and it will work perfectly... until the cache is cleared again. Please help.

Edit: Narrowed the problem down further, when I clear the cache, if I try to encode a string with 2 characters or less, it crashes. I believe that's why the `$user->id` won't encode, because it's 1 char long. I tried encoding '1', '12', '123', '1234'. It works from '123' going but for it to work for '12' or '1', I have to encode something 3 chars long first.

**Comment by vinkla** [comment]
Are you using the default or custom configuration (alphabet, salt, lenght)?

**Comment by niiapa** [comment]
My settings, minus my salt:
`'main' => [
            'salt' => 'string123456',
            'length' => '8',
			'alphabet' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
        ],`

**Comment by vinkla** [comment]
Sorry, not sure what is going on in your environment. The tests are green. Please provide failing tests on the `hashids/hashids` package and then we can take a look at it.

**Comment by vailancio** [comment]
I am having exact same issue from past year on my Mac OS X dev machine but not on production linux server.

**Comment by niiapa** [comment]
@vailancio Interesting. I'm running Sierra on my machine, perhaps that's the issue. For now to workaround it, I'm encoding random long strings before encoding what I need. Thanks for the info though.
