### ISSUE TITLE
hashids stopped encoding long string

### ISSUE THREAD

**Issue by ctf0** [vinkla/laravel-hashids#70]
am using current system time to make sure the created ids never collide 
```php
system('date +%s%N')
```

but recently the lib stopped working and started to give empty string instead, ex.
```php
Hashids::encode(1508058326172617500) // 20 digits
```
will give `""`, but if we reduced the number
```php
Hashids::encode(150805832) // 9 digits
```
it will work `"bzeoONEa"`

any reason why this is happening ?

btw testing the same long number on https://codepen.io/ivanakimov/pen/bNmExm works

**Comment by vinkla** [comment]
Please open this in the official Hashids package for PHP. This is just a Laravel wrapper.

**Comment by DEVESH-2030** [comment]
How to encode string value?

ex: "development"
