### ISSUE TITLE
Can't install in Laravel 5.2.45

### ISSUE THREAD

**Issue by fastinphp** [vinkla/laravel-hashids#71]
When I try install I get next:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vinkla/hashids ^3.3 -> satisfiable by vinkla/hashids[3.3.0].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - vinkla/hashids 3.3.0 requires illuminate/contracts 5.5.* -> satisfiable by illuminate/contracts[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/contracts v5.5.0|don't install laravel/framework v5.2.45
    - don't install illuminate/contracts v5.5.16|don't install laravel/framework v5.2.45
    - don't install illuminate/contracts v5.5.17|don't install laravel/framework v5.2.45
    - don't install illuminate/contracts v5.5.2|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

Installation failed, reverting ./composer.json to its original content.

What I need to try?

**Comment by Sarav-S** [comment]
Hi,

You should try installing 2.2.0 release instead of 3.3.0 release.

`composer require vinkla/hashids 2.2.0`

or try adding it to composer.json's require by

`"vinkla/hashids": "2.2.0"`

**Comment by vinkla** [comment]
Thanks for helping out @Sarav-S!

**Comment by MarceloBonifazio** [comment]
The same problem in Laravel v5.3.31
Which version should I install? 3.2.0?
