### ISSUE TITLE
Installation problem on laravel v5.4.36

### ISSUE THREAD

**Issue by miladsalehi** [vinkla/laravel-hashids#72]
Problem 1
    - Installation request for vinkla/hashids ^3.3 -> satisfiable by vinkla/hashids[3.3.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - vinkla/hashids 3.3.0 requires illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].

how can i fix that?
thanks

**Comment by vinkla** [comment]
Update to the latest version of PHP and Laravel.
