### ISSUE TITLE
Duplicate hash

### ISSUE THREAD

**Issue by rexxnar** [vinkla/laravel-hashids#73]
We are hashing ID's of objects and save them in the database. Now we got 2 same hashes encoded by ```Hashids::encode(1290)``` and ```Hashids::encode(1302)``` now those same numbers encode in the following hash: ```3GWpmbk4xdzJn4z```
Now the package delivers a decode function: ```Hashids::decode('3GWpmbk4xdzJn4') ``` and it gives back an array with 1 item that has 1302. This matches the 2nd number encoded but not the first? It should either decode in both numbers, or the hash should be different for the numbers.

Any clue how this is possible or is this the behavier is need to have? We are using version v1.1.0 since the project is still running in laravel 5.1 and needs to be upgraded soon.

Edit* For version 3.3.0 the problem has been solved.

**Comment by vinkla** [comment]
We've cleaned up and fixed a couple of bugs in Hashids version 2.0.
