### ISSUE TITLE
Hashids::decode does not work randomly.

### ISSUE THREAD

**Issue by imzeeshan** [vinkla/laravel-hashids#75]
Hi 
I have a strange behavior happening in my code, \Hashids::decode works on certain routes/controllers but on another route/controller it does not. 

The variable is the same with the same value, any help in the right path would be appreciated. 

Thanks.

**Comment by vinkla** [comment]
Hey, please always provide snippets of code when asking for help. Stating that it doesn't work in your environment makes it hard for us to help you.
