### ISSUE TITLE
Add Laravel 5.6 Support

### ISSUE THREAD

**Issue by johannesschobel** [vinkla/laravel-hashids#77]
Hey @vinkla ,
is it possible to add `Laravel 5.6` support for this package?

You would need to change the `composer.json` file accordingly:
```
    "require": {
        "php": "^7.1.3",
        "graham-campbell/manager": "^3.0",
        "hashids/hashids": "^2.0",
        "illuminate/contracts": "5.5.*|5.6.*",
        "illuminate/support": "5.5.|5.6.*"
    },
    "require-dev": {
        "graham-campbell/analyzer": "^2.0",
        "graham-campbell/testbench": "^5.0",
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^6.5|~7.0"
},
```

This should, hopefully, do the trick ;)
Would be awesome to update the package to the latest changes!

Cheers and thank you very much!

**Comment by vinkla** [comment]
Hey, it isn't possible just yet https://github.com/vinkla/laravel-hashids/pull/76#issuecomment-364033751

**Comment by johannesschobel** [comment]
Damn.. I knew there are some "nasty" dependencies that kept you from updating your package 😆 sorry for adding another issue

**Comment by sebdesign** [comment]
https://github.com/GrahamCampbell/Laravel-Manager/pull/11 has been merged now!

**Comment by johannesschobel** [comment]
you are a beast! awesome - thank you so much!
