### ISSUE TITLE
Laravel 5.6 Support

### ISSUE THREAD

**Issue by bhuvidya** [vinkla/laravel-hashids#79]
Thanks for this package, it's great! I use it with a model trait to provide automatic hashing for database records.

I am keen to upgrade my applications to Laravel 5.6 - any chance you could make this package L5.6 compatible?

Cheers

**Comment by vinkla** [comment]
Laravel 5.6 support isn't possible just yet: https://github.com/GrahamCampbell/Laravel-Manager/pull/11#issuecomment-364654625
