### ISSUE TITLE
No support for lumen 5.5 ?

### ISSUE THREAD

**Issue by devcodebakerz** [vinkla/laravel-hashids#80]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install vinkla/hashids 4.0.0
    - Conclusion: remove illuminate/contracts v5.5.34
    - Installation request for vinkla/hashids ^4.0 -> satisfiable by vinkla/hashids[4.0.0, 4.0.x-dev].
    - Conclusion: don't install illuminate/contracts v5.5.34
    - vinkla/hashids 4.0.x-dev requires illuminate/contracts 5.6.* -> satisfiable by illuminate/contracts[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3].
    - Can only install one of: illuminate/contracts[5.6.x-dev, v5.5.34].
    - Can only install one of: illuminate/contracts[v5.6.0, v5.5.34].
    - Can only install one of: illuminate/contracts[v5.6.1, v5.5.34].
    - Can only install one of: illuminate/contracts[v5.6.2, v5.5.34].
    - Can only install one of: illuminate/contracts[v5.6.3, v5.5.34].
    - Installation request for illuminate/contracts (locked at v5.5.34) -> satisfiable by illuminate/contracts[v5.5.34].

Installation failed, reverting ./composer.json to its original content.

**Comment by vinkla** [comment]
Version 3.0 supports Lumen.

**Comment by devcodebakerz** [comment]
Thanks. Look forward to it.
