### ISSUE TITLE
With Reference to  issue #80

### ISSUE THREAD

**Issue by devcodebakerz** [vinkla/laravel-hashids#81]
I went ahead with your solution as provided by you in issue #80 , I am still not able to install your package, version 3.0 requires, illuminate/contracts 5.2.* and lumen 5.5 has to have 5.5.*..  Please let me know if it can be used at all with lumen 5.5.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove illuminate/contracts v5.5.34
    - Conclusion: remove laravel/lumen-framework v5.5.2
    - Conclusion: don't install laravel/lumen-framework v5.5.2
    - Conclusion: don't install laravel/lumen-framework v5.5.1
    - Conclusion: don't install laravel/lumen-framework v5.5.0
    - Installation request for laravel/lumen-framework 5.5.* -> satisfiable by laravel/lumen-framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.2].
    - Conclusion: don't install illuminate/contracts v5.3.23
    - Conclusion: don't install illuminate/contracts v5.5.0|install illuminate/contracts v5.3.23
    - Conclusion: don't install illuminate/contracts v5.5.2|install illuminate/contracts v5.3.23
    - Conclusion: don't install illuminate/contracts v5.5.16|install illuminate/contracts v5.3.23
    - Conclusion: don't install illuminate/contracts v5.5.17|install illuminate/contracts v5.3.23
    - Conclusion: don't install illuminate/contracts v5.5.28|install illuminate/contracts v5.3.23
    - Installation request for vinkla/hashids 3.0 -> satisfiable by vinkla/hashids[3.0.0].
    - Conclusion: don't install illuminate/contracts v5.5.33|install illuminate/contracts v5.3.23
    - vinkla/hashids 3.0.0 requires illuminate/contracts 5.2.* || 5.3.* -> satisfiable by illuminate/contracts[5.2.x-dev, 5.3.x-dev, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - Can only install one of: illuminate/contracts[5.5.x-dev, 5.3.x-dev].
    - Can only install one of: illuminate/contracts[v5.3.0, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.3.16, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.3.4, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[5.5.x-dev, 5.2.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.0, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.19, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.21, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.24, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.25, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.26, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.27, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.28, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.31, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.32, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.37, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.43, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.45, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.6, 5.5.x-dev].
    - Can only install one of: illuminate/contracts[v5.2.7, 5.5.x-dev].
    - laravel/lumen-framework 5.5.x-dev requires illuminate/contracts 5.5.* -> satisfiable by illuminate/contracts[v5.5.34, 5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33].
    - Conclusion: don't install illuminate/contracts v5.5.34|install illuminate/contracts v5.3.23

**Comment by vinkla** [comment]
Try using the latest version of 3.0 which is 3.3.

**Comment by devcodebakerz** [comment]
Yes, it worked, when I tried with that version, should have first reported here. Thanks.
