### ISSUE TITLE
[FEATURE REQUEST] Hash all ids within a collection

### ISSUE THREAD

**Issue by iec989** [vinkla/laravel-hashids#85]
I strongly believe it would be a great functionallity to have a built-in solution that would encode all the IDs within a collection - is this in the roadmap?

**Comment by vinkla** [comment]
Thanks for the suggestion. This is just a Laravel wrapper around the Hashids library and we don't have any plans to build in any custom solutions.

**Comment by GrahamCampbell** [comment]
Just map over the collection. Much better to compose things like that yourself than to have a specialized function to do it.
