### ISSUE TITLE
Why was Laravel 5.5 support removed?

### ISSUE THREAD

**Issue by finalgamer** [vinkla/laravel-hashids#86]
I would like to use hashids v3 with laravel 5.5 but this is currently not possible because this package is blocking it.

**Comment by vinkla** [comment]
Because I don’t want to maintain older versions. I suggest you upgrade to 5.6.

**Comment by GrahamCampbell** [comment]
Laravel 5.5 is not an old version technically, it is LTS.

**Comment by alihastam** [comment]
this version support  Laravel 5.5 

"vinkla/hashids": "3.3.0"

Require
php ^7.0
illuminate/contracts 5.5.*
illuminate/support 5.5.*
graham-campbell/manager ^3.0

**Comment by GrahamCampbell** [comment]
Yes, but doesn't work with manager 4.0, so excludes use with any other packages. I've had to fork this package in order to use it at all.
