### ISSUE TITLE
 Return value of Vinkla\Hashids\HashidsServiceProvider::registerFactory() must be an instance of Vinkla\Hashids\void, none returned 

### ISSUE THREAD

**Issue by davmixcool** [vinkla/laravel-hashids#90]
I recently encountered this error on laravel 5.6:
`local.ERROR: Return value of Vinkla\Hashids\HashidsServiceProvider::registerFactory() must be an instance of Vinkla\Hashids\void, none returned.
`
Any help is appreciated. Thanks?

Full Error
`[2018-06-18 13:59:28] local.ERROR: Return value of Vinkla\Hashids\HashidsServiceProvider::registerFactory() must be an instance of Vinkla\Hashids\void, none returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of Vinkla\\Hashids\\HashidsServiceProvider::registerFactory() must be an instance of Vinkla\\Hashids\\void, none returned at /opt/workspace/web/designer/vendor/vinkla/hashids/src/HashidsServiceProvider.php:81)
[stacktrace]
#0 /opt/workspace/web/designer/vendor/vinkla/hashids/src/HashidsServiceProvider.php(64): Vinkla\\Hashids\\HashidsServiceProvider->registerFactory()
#1 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(573): Vinkla\\Hashids\\HashidsServiceProvider->register()
#2 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Vinkla\\Hashids\\HashidsServiceProvider))
#3 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(548): Illuminate\\Foundation\\ProviderRepository->load(Array)
#4 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#5 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#6 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#7 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#8 /opt/workspace/web/designer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#9 /opt/workspace/web/designer/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#10 {main}
"} `

**Comment by vinkla** [comment]
Try updating to PHP 7.1 or later.
