### ISSUE TITLE
[L5.6] Missing BC Math or GMP extension

### ISSUE THREAD

**Issue by mohamedsabil83** [vinkla/laravel-hashids#93]
What I need to do to solve this problem as shown in the image below.
My PHP version is 7.1 and php7.1-bcmath is installed

![screenshot from 2018-07-23 21-21-29](https://user-images.githubusercontent.com/10126040/43095905-00ad2fbc-8ec0-11e8-89a4-b8e6eb80390f.png)

**Comment by vinkla** [comment]
Hmm, it seems the bcmath extension is missing or disabled. Does the bcmath extension show if you run `phpinfo`?

**Comment by mohamedsabil83** [comment]
yes it's
![screenshot from 2018-07-24 00-46-02](https://user-images.githubusercontent.com/10126040/43104714-fdf7aaf2-8eda-11e8-8c5a-39f0516657fb.png)

**Comment by mohamedsabil83** [comment]
Seems there is a problem with the previous installation. I remove it and re-install bcmath extension and restart apache2 and it's working now like a charm.

Sorry about this and thank you for your attention.
