### ISSUE TITLE
 "Class 'App\Hashids' not found"

### ISSUE THREAD

**Issue by pmochine** [vinkla/laravel-hashids#94]
What am I doing wrong? (Laravel 5.6)

In config/app.php (aliases)

         //....
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
        'Image' => Intervention\Image\Facades\Image::class,
        'Socialite' => Laravel\Socialite\Facades\Socialite::class,
        'Location' => Stevebauman\Location\Facades\Location::class,

        //https://github.com/vinkla/laravel-hashids
        'Hashids' => Vinkla\Hashids\Facades\Hashids::class

In my model I'm trying to call

    public function getIdAttribute($id){
        return Hashids::encode($id);
    }

p.S. If I add the facade in model everything works fine. I tried cache:clear as well

**Comment by vinkla** [comment]
Try adding this in the top of your model file:

```php
use Vinkla\Hashids\Facades\Hashids;
```
It should do the trick.

**Comment by pmochine** [comment]
I wrote 

>  If I add the facade in model everything works fine

But for future readers, just use it like: \Hashids::encode($id); then it works
