### ISSUE TITLE
Laravel 5.5 cannot install hashids

### ISSUE THREAD

**Issue by eluotao** [vinkla/laravel-hashids#97]
Laravel 5.5 cannot install hashids
Error message:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vinkla/hashids ^5.0 -> satisfiable by vinkla/hashids[5.0.0].
    - Conclusion: remove laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.40
    - vinkla/hashids 5.0.0 requires illuminate/support 5.6.* -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, V5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5. 6.27, v5.6.28, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/support v5.6.4|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.5|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.6|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.7|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.5.40
    - illuminate/support v5.6.10 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.11 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.12 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.13 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.14 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.15 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.16 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.17 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.19 conflicts with laravel/framework[v5.5.40].
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.5.40
    - illuminate/support v5.6.20 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.21 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.22 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.23 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.24 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.25 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.26 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.27 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.28 conflicts with laravel/framework[v5.5.40].
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.5.40
    - illuminate/support v5.6.8 conflicts with laravel/framework[v5.5.40].
    - illuminate/support v5.6.9 conflicts with laravel/framework[v5.5.40].
    - Installation request for laravel/framework (locked at v5.5.40, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.40].

Installation failed, reverting ./composer.json to its original content.

**Comment by vinkla** [comment]
[I suggest you upgrade to Laravel 5.7.](https://laravel.com/docs/5.7/upgrade)

**Comment by huggy06** [comment]
Hello
I have exact same problem with Laravel 5.7. Any solution ?

**Comment by vinkla** [comment]
```sh
$ composer require "vinkla/hashids:^7.1"
```

**Comment by huggy06** [comment]
Thanks

I got this message

 [InvalidArgumentException]
  Could not find package vinkla/hashids in a version matching ^7.1


Le mer. 27 mars 2019 à 10:21, Vincent Klaiber <notifications@github.com> a
écrit :

**Comment by vinkla** [comment]
Oh, it should have been `^5.1`. I've updated the comment.

**Comment by huggy06** [comment]
Thanks !

Le mer. 27 mars 2019 à 10:31, Vincent Klaiber <notifications@github.com> a
écrit :

**Comment by huggy06** [comment]
Juste one more question

I henerate url in a list with

{{
route('evaluation.soft.edit',['evaluation'=>$evaluation->id,'soft'=>$soft->id,
'score'=>$soft->pivot->score])}}

that generate this url
http://localhost:8000/admin/evaluations/evaluateur/115


I follow all your tutorial, it seems url is is not masked

Maybe I miss something ?

**Comment by HadiNiazi** [comment]
If you are facing this issue, please specify the steric to pull any compatible version.
Before
~~~
composer require vinkla/hashids
~~~
After
~~~
composer require vinkla/hashids:*
~~~
